/** @type {import("tailwindcss").Config} */
const spacingScale = {
  px: "1px",
  0: "0px",
  0.5: "0.125rem",
  1: "0.25rem",
  1.5: "0.375rem",
  2: "0.5rem",
  2.5: "0.625rem",
  3: "0.75rem",
  3.5: "0.875rem",
  4: "1rem",
  5: "1.25rem",
  6: "1.5rem",
  7: "1.75rem",
  8: "2rem",
  9: "2.25rem",
  10: "2.5rem",
  11: "2.75rem",
  12: "3rem",
  14: "3.5rem",
  16: "4rem",
  20: "5rem",
  24: "6rem",
  28: "7rem",
  32: "8rem",
  36: "9rem",
  40: "10rem",
  44: "11rem",
  48: "12rem",
};

const config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    "--spacing": "0.25rem",
    spacing: spacingScale,
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        xs: ["var(--text-xs)", { lineHeight: "1.5rem" }],
        sm: ["var(--text-sm)", { lineHeight: "1.5rem" }],
        base: ["var(--text-base)", { lineHeight: "1.5rem" }],
        lg: ["var(--text-lg)", { lineHeight: "1.5rem" }],
        xl: ["var(--text-xl)", { lineHeight: "1.5rem" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "2rem" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "2.25rem" }],
        "4xl": ["var(--text-4xl)", { lineHeight: "2.5rem" }],
      },
    },
    colors: {
      background: "var(--bg-base)",
      foreground: "var(--text-primary)",
      card: "var(--bg-base)",
      "card-foreground": "var(--text-primary)",
      popover: "var(--bg-base)",
      "popover-foreground": "var(--text-primary)",
      primary: "var(--interactive-default)",
      "primary-foreground": "var(--text-inverse)",
      secondary: "var(--bg-subtle)",
      "secondary-foreground": "var(--text-primary)",
      muted: "var(--bg-muted)",
      "muted-foreground": "var(--text-secondary)",
      accent: "var(--bg-subtle)",
      "accent-foreground": "var(--text-primary)",
      destructive: "var(--danger-600)",
      "destructive-foreground": "var(--text-inverse)",
      border: "var(--border-default)",
      input: "var(--border-default)",
      ring: "var(--interactive-default)",
      "input-background": "var(--input-background)",
      brand: {
        primary: "var(--brand-primary)",
        hover: "var(--brand-hover)",
        light: "var(--brand-light)",
      },
      scanner: {
        bg: {
          dark: "var(--bg-scanner-dark)",
          panel: "var(--bg-scanner-panel)",
          button: {
            muted: "var(--bg-button-muted)",
            default: "var(--bg-button-default)",
            hover: "var(--bg-button-hover)",
          },
          semiDark: "var(--bg-semi-dark)",
        },
        border: {
          buttonLight: "var(--border-button-light)",
          inset: "var(--border-inset)",
          default: "var(--border-scanner)",
        },
        text: {
          light: "var(--text-scanner-light)",
          secondary: "var(--text-secondary-muted)",
        },
      },
      "scanner-default": "var(--color-scanner-default)",
      "scanner-hover": "var(--color-scanner-hover)",
      "scanner-border": "var(--color-scanner-border)",
      "scanner-text": "var(--color-scanner-text)",
      led: {
        green: "var(--led-green)",
        red: "var(--led-red)",
      },
    },
    boxShadow: {
      button: "var(--shadow-button)",
      inset: "var(--shadow-inset)",
      glow: "var(--shadow-glow)",
      brand: "0 0 15px rgba(239, 153, 31, 0.3)",
      "brand-lg": "0 0 20px rgba(239, 153, 31, 0.5)",
      "brand-inset": "inset 0 0 10px rgba(239, 153, 31, 0.1)",
    },
    borderRadius: {
      "scanner-xs": "var(--radius-xs)",
      "scanner-sm": "var(--radius-sm)",
      "scanner-md": "var(--radius-md)",
      "scanner-display": "var(--radius-display)",
    },
  },
  plugins: [],
};

module.exports = config;
